version: '3.7'

services:
  # frontend:
  #   build:
  #     context: .
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - nignx
  certbot:
    image: certbot/certbot
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:1.23.4-alpine
    volumes:
      # - type: bind
      #   source: ./proxy/nginx.conf
      #   target: /etc/nginx/conf.d/default.conf
      #   read_only: true

      # for docker ssl
      - ./proxy:/etc/nginx/conf.d
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on: 
      - api
  api:
    build:
      context: .
    container_name: morethanjustlinks-go
    volumes:
      - .:/morethanjustlinks/
    environment:
      - GIN_MODE=release 
    depends_on:
      maria-db:
        condition: service_healthy
  maria-db:
    image: mariadb:10-focal
    container_name: morethanjustlinks-maria-db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --password=secret --silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    expose:
      - 3306
    # setting some env vars to create the DB
    environment:
      MYSQL_ROOT_PASSWORD: "secret"   
      MYSQL_DATABASE: "morethanjustlinks_db"

    # we mount a data volume to make sure we don't lose data
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

